### ISSUE TITLE
unknown fuction 'format'

### ISSUE THREAD

**Issue by reppard** [terraform-community-modules/tf_aws_coreos_ami#1]
Hello,
I've been trying to wrap my head around these modules.  When I do terraform get and terraform apply, terraform barks the following at me:

Error creating plan: 1:23: unknown function called: format in:
${lookup(var.all_amis, format("%s-%s-%s", var.channel, var.region, var.virttype))}

Also is it necessary to cd into .terraform/modules/<sha i'm assuming> and run make?  If so I think it would be useful to add that to the README.  Thanks for the help and good work!

**Comment by bobtfish** [comment]
format was added in terraform 0.4.0, you need to be using at least this version for this module to work :)

And you're right about the make - I have a common pattern I've written about (on my blog at bobtfish.github.io) which I always use, but that wasn't in the documentation here - I've added a note now!

**Comment by reppard** [comment]
I could have sworn I had 0.4+ but alas you are correct sir!  I still had 0.3.7 sitting around.  Thanks for the feed back!
