### ISSUE TITLE
Variable 'all_amis' duplicate found

### ISSUE THREAD

**Issue by llinder** [terraform-community-modules/tf_aws_coreos_ami#10]
Including the 'all_amis' variable breaks multi module configuration where each of my modules reference this module.

**Comment by antonbabenko** [comment]
Could you please paste sample config which breaks it ?

**Comment by llinder** [comment]
For an example I have 2 modules (A,B) where both modules include:

```
module "ami" {
  source = "github.com/terraform-community-modules/tf_aws_coreos_ami/instance_type"
  region = "${var.region}"
  channel = "stable"
  instance_type = "${var.instance_type}"
}
```

These modules are executed with Make where Terraform command is called like:
`terraform apply -target module.B`

**Comment by antonbabenko** [comment]
@llinder try now, thanks @girishramnani :)

**Comment by llinder** [comment]
That fixes it.  Thanks!
