### ISSUE TITLE
unknown variable referenced: 'all_amis' error on make in terraform 0.7.4

### ISSUE THREAD

**Issue by girishramnani** [terraform-community-modules/tf_aws_coreos_ami#7]
I am using terraform 0.7.4, and when i do `make`. 
this is the make file i have.

```
.PHONY: all

all: load_dependencies

load_dependencies:
    terraform get
    for i in $$(ls .terraform/modules/*/Makefile); do i=$$(dirname $$i); make -C $$i; done

```

This error happens.

```
Error loading Terraform: module ami.root: 1 error(s) occurred:

* output 'ami_id': unknown variable referenced: 'all_amis'. define it with 'variable' blocks

```

**Comment by antonbabenko** [comment]
Can it be related to the [notes section in readme](https://github.com/terraform-community-modules/tf_aws_coreos_ami#note) ? There is no `make load_dependencies` which you can use, but there is `make`.

**Comment by girishramnani** [comment]
yeah my bad, corrected. error happens when I do a `make` , i have also added the makefile and it seems its due to the strict variable checks which was added in terraform 0.7.

**Comment by paultyng** [comment]
It doesn't seem to harm anything for me, so i typically just do a `terraform get || true` to skip past it, since terraform still seems to get the modules and I can still build them, just exits non-zero.

**Comment by jonaskint** [comment]
I'm having the same issue on terraform 0.7.3 and 0.7.7.
Is there any workaround at the moment?

**Comment by antonbabenko** [comment]
Please try now and let us know if there is still a problem
